esphome:
  name: 242room
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "WiFi_Gratis!"
  password: "LaWifiGratisDePabloElFisico!"
  manual_ip:
    static_ip: 192.168.12.192
    gateway: 192.168.12.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "242Room Fallback Hotspot"
    password: "7cw5NsuWR1Ip"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "OTA"

ota:
  password: "OTA"

# Temperature and humidity sensor
sensor:
  - platform: dht
    model: DHT11
    pin: GPIO15
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
    

### radio
remote_transmitter:
  pin: GPIO02
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%
  
switch:

  - platform: template
    name: "Plug A"
    icon: "mdi:laptop"
    optimistic: true
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110011110001000110110000'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000101100101000110000'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000001001010101000000'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110011101101001001110000'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110010010100101110010000'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110010000111111110100000'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110001011111000000100000'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000110110010000010000'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
 

  - platform: template
    name:  Plug B
    icon: "mdi:lamp"
    optimistic: true
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000101100101000110100'
          protocol: 5
          repeat: 
            times: 10
            wait_time: 0s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110011110001000110110100'
          protocol: 5
          repeat: 
            times: 4
            wait_time: 0s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110011101101001001110100'
          protocol: 5
          repeat: 
            times: 4
            wait_time: 0s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000001001010101000100'
          protocol: 5
          repeat: 
            times: 4
            wait_time: 0s
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000110110010000010100'
          protocol: 5
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110001011111000000100100'
          protocol: 5
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110010000111111110100100'
          protocol: 5
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110010010100101110010100'
          protocol: 5


  - platform: template
    name: Plug C
    icon: "mdi:led-on"
    optimistic: true
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110011101101001001111100'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000001001010101001100'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000101100101000111100'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110011110001000110111100'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110010000111111110101100'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110010010100101110011100'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000110110010000011100'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110001011111000000101100'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s


  - platform: template
    name: "Plug D"
    icon: "mdi:lightbulb"
    optimistic: true
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110010000111111110100010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110001011111000000100010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000110110010000010010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110010010100101110010010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000101100101000110010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000001001010101000010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110011101101001001110010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110011110001000110110010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
 

  - platform: template
    name: "Master"
    icon: "mdi:widgets"
    optimistic: true
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110001011111000000101010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000110110010000011010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110010010100101110011010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110010000111111110101010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110011101101001001111010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110011110001000110111010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000101100101000111010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
      - remote_transmitter.transmit_rc_switch_raw:
          code: '110000001001010101001010'
          protocol: 5
          repeat: 
            times: 3
            wait_time: 0.5s
 


